#!/usr/bin/env python3
"""Provision upstream MCP servers from servers/*/manifest.yaml.

Scans every directory under servers/ for a manifest.yaml, then:
  - kind: stdio   -> runs `setup` commands once (re-runs when setup changes),
                     registers a stdio entry (command/args/cwd/env).
  - kind: docker  -> builds the image, emits a service into
                     docker-compose.servers.yml, registers a streamable_http/sse
                     entry reachable by compose service name (or 127.0.0.1 with --host).
  - kind: remote  -> registers the given url as-is (no build).

Outputs (both auto-generated, do not edit by hand):
  config/registry.generated.yaml   merged by the gateway with config/registry.yaml
                                   (hand-written registry.yaml wins on id conflict)
  docker-compose.servers.yml       run with:
                                   docker compose -f docker-compose.yml -f docker-compose.servers.yml up

Usage:
  python provision.py              # provision for gateway running in compose
  python provision.py --host      # gateway runs on the host (python -m gateway):
                                   # docker servers publish ports, urls use 127.0.0.1
  python provision.py --force     # re-run setup / rebuild images even if unchanged
  python provision.py --only ID   # provision a single server
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent
SERVERS_DIR = ROOT / "servers"
CONFIG_DIR = ROOT / "config"
GENERATED_REGISTRY = CONFIG_DIR / "registry.generated.yaml"
COMPOSE_SERVERS = ROOT / "docker-compose.servers.yml"
MARKER_NAME = ".provisioned"

# Must match gateway.merge: no "__", safe charset.
SAFE_ID = re.compile(r"^[A-Za-z0-9._-]+$")

GENERATED_HEADER = (
    "# AUTO-GENERATED by provision.py — DO NOT EDIT.\n"
    "# Hand-written servers belong in registry.yaml (it wins on id conflicts).\n"
)


class ManifestError(ValueError):
    pass


def fail(msg: str) -> None:
    print(f"provision: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def run(cmd: list[str] | str, cwd: Path, shell: bool = False) -> None:
    print(f"  $ {cmd if isinstance(cmd, str) else ' '.join(cmd)}")
    subprocess.run(cmd, cwd=cwd, shell=shell, check=True)


def load_manifest(path: Path) -> dict[str, Any]:
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise ManifestError(f"{path}: manifest must be a YAML mapping")
    return doc


def validate_id(server_id: str, src: Path) -> None:
    if not SAFE_ID.match(server_id) or "__" in server_id:
        raise ManifestError(
            f"{src}: invalid server id {server_id!r} "
            f"(must match [A-Za-z0-9._-]+ and not contain '__')"
        )


def setup_fingerprint(setup: list[str]) -> str:
    return hashlib.sha256(json.dumps(setup).encode()).hexdigest()


def needs_setup(server_dir: Path, setup: list[str], force: bool) -> bool:
    if force:
        return True
    marker = server_dir / MARKER_NAME
    if not marker.exists():
        return True
    return marker.read_text().strip() != setup_fingerprint(setup)


def mark_provisioned(server_dir: Path, setup: list[str]) -> None:
    (server_dir / MARKER_NAME).write_text(setup_fingerprint(setup))


def provision_stdio(server_id: str, server_dir: Path, m: dict[str, Any], force: bool) -> dict[str, Any]:
    command = m.get("command")
    if not isinstance(command, list) or not command:
        raise ManifestError(f"{server_dir}: stdio manifest needs `command: [exe, arg, ...]`")
    setup = [str(s) for s in (m.get("setup") or [])]
    if setup and needs_setup(server_dir, setup, force):
        print(f"[{server_id}] running setup ...")
        for step in setup:
            run(step, cwd=server_dir, shell=True)
        mark_provisioned(server_dir, setup)
    elif setup:
        print(f"[{server_id}] setup unchanged, skipping (use --force to re-run)")
    entry: dict[str, Any] = {
        "transport": "stdio",
        "command": str(command[0]),
        "args": [str(a) for a in command[1:]],
        "cwd": str(server_dir.relative_to(ROOT)),
    }
    if m.get("env"):
        entry["env"] = {str(k): str(v) for k, v in m["env"].items()}
    return entry


def provision_docker(
    server_id: str, server_dir: Path, m: dict[str, Any], host_mode: bool
) -> tuple[dict[str, Any], dict[str, Any]]:
    port = m.get("port")
    if not isinstance(port, int):
        raise ManifestError(f"{server_dir}: docker manifest needs integer `port`")
    transport = m.get("transport", "streamable_http")
    if transport not in ("streamable_http", "sse"):
        raise ManifestError(f"{server_dir}: docker transport must be streamable_http or sse")
    path = m.get("path", "/mcp" if transport == "streamable_http" else "/sse")
    dockerfile_name = str(m.get("dockerfile", "Dockerfile"))
    context = server_dir / str(m.get("build", "."))
    dockerfile = context / dockerfile_name
    if not dockerfile.exists():
        raise ManifestError(f"{server_dir}: no Dockerfile at {dockerfile}")
    tag = f"mcp-server-{server_id}:latest"

    # The image is built by `docker compose up --build`, not here: provision only
    # emits the build context into docker-compose.servers.yml. This keeps provision
    # a pure config generator, so it can itself run in a container with no Docker
    # socket. `--force` rebuilds are the compose layer's job now (`--no-cache`).
    print(f"[{server_id}] emitting compose build for image {tag} (built by `compose up --build`) ...")
    service: dict[str, Any] = {
        "build": {
            "context": str(context.relative_to(ROOT)),
            "dockerfile": dockerfile_name,
        },
        "image": tag,
        "restart": "unless-stopped",
    }
    if m.get("env"):
        # Values pass through verbatim, so `${VAR}` / `${VAR:-default}` are
        # interpolated by `docker compose up` from the root .env (keeps secrets
        # out of the committed manifest).
        service["environment"] = {str(k): str(v) for k, v in m["env"].items()}
    if m.get("env_file"):
        # Per-server env file(s), relative to servers/<id>/, loaded into the
        # container by compose (e.g. `.env` next to the manifest).
        raw_files = m["env_file"]
        files = raw_files if isinstance(raw_files, list) else [raw_files]
        resolved: list[str] = []
        for f in files:
            p = (server_dir / str(f)).resolve()
            try:
                resolved.append(str(p.relative_to(ROOT)))
            except ValueError:
                raise ManifestError(f"{server_dir}: env_file {f!r} must be inside the repo")
        service["env_file"] = resolved
    if m.get("command"):
        service["command"] = [str(c) for c in m["command"]]
    if host_mode:
        service["ports"] = [f"{port}:{port}"]
        url = f"http://127.0.0.1:{port}{path}"
    else:
        url = f"http://{server_id}:{port}{path}"

    entry: dict[str, Any] = {"transport": transport, "url": url}
    if m.get("headers"):
        entry["headers"] = {str(k): str(v) for k, v in m["headers"].items()}
    return entry, service


def provision_remote(server_dir: Path, m: dict[str, Any]) -> dict[str, Any]:
    url = m.get("url")
    if not url:
        raise ManifestError(f"{server_dir}: remote manifest needs `url`")
    transport = m.get("transport", "streamable_http")
    if transport not in ("streamable_http", "sse"):
        raise ManifestError(f"{server_dir}: remote transport must be streamable_http or sse")
    entry: dict[str, Any] = {"transport": transport, "url": str(url)}
    if m.get("headers"):
        entry["headers"] = {str(k): str(v) for k, v in m["headers"].items()}
    return entry


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", action="store_true", help="gateway runs on the host, not in compose")
    ap.add_argument("--force", action="store_true", help="re-run setup / rebuild images")
    ap.add_argument("--only", metavar="ID", help="provision a single server id")
    args = ap.parse_args()

    if not SERVERS_DIR.is_dir():
        fail(f"servers/ directory not found at {SERVERS_DIR}")

    manifests = sorted(SERVERS_DIR.glob("*/manifest.yaml"))
    if not manifests:
        print("provision: no servers/*/manifest.yaml found, nothing to do")

    registry_servers: dict[str, Any] = {}
    compose_services: dict[str, Any] = {}
    errors: list[str] = []

    for mf in manifests:
        server_dir = mf.parent
        try:
            m = load_manifest(mf)
            server_id = str(m.get("id", server_dir.name))
            validate_id(server_id, mf)
            if args.only and server_id != args.only:
                continue
            if server_id in registry_servers:
                raise ManifestError(f"{mf}: duplicate server id {server_id!r}")
            kind = m.get("kind")
            if kind == "stdio":
                registry_servers[server_id] = provision_stdio(server_id, server_dir, m, args.force)
            elif kind == "docker":
                entry, service = provision_docker(server_id, server_dir, m, args.host)
                registry_servers[server_id] = entry
                compose_services[server_id] = service
            elif kind == "remote":
                registry_servers[server_id] = provision_remote(server_dir, m)
            else:
                raise ManifestError(f"{mf}: `kind` must be stdio, docker, or remote (got {kind!r})")
            print(f"[{server_id}] OK ({kind})")
        except (ManifestError, subprocess.CalledProcessError, yaml.YAMLError) as e:
            errors.append(f"{server_dir.name}: {e}")
            print(f"[{server_dir.name}] FAILED: {e}", file=sys.stderr)

    CONFIG_DIR.mkdir(exist_ok=True)
    GENERATED_REGISTRY.write_text(
        GENERATED_HEADER + yaml.safe_dump({"servers": registry_servers}, sort_keys=True),
        encoding="utf-8",
    )
    print(f"wrote {GENERATED_REGISTRY.relative_to(ROOT)} ({len(registry_servers)} servers)")

    COMPOSE_SERVERS.write_text(
        GENERATED_HEADER + yaml.safe_dump({"services": compose_services or {}}, sort_keys=True),
        encoding="utf-8",
    )
    print(f"wrote {COMPOSE_SERVERS.relative_to(ROOT)} ({len(compose_services)} docker services)")

    if errors:
        fail(f"{len(errors)} server(s) failed: " + "; ".join(errors))
    print("provision: done. Restart the gateway to pick up changes (Tool-RAG syncs on startup).")


if __name__ == "__main__":
    main()
